### ISSUE TITLE
Emotes in ~4 day period can't be resolved with extensionless CDN link

### ISSUE THREAD

**Issue by jammehcow** [SevenTV/API#52]
Emotes uploaded between `2022-07-13T08:14:00` and `2022-07-17T13:112:00` are unable to be resolved with their extensionless CDN link (e.g. https://cdn.7tv.app/emote/62d40ad49be195fd6d68a23b/4x). This causes chatterino to fail when rending the emote as it receives a bad result.

Issue appears to have started from this emote ID (conveniently uploaded by @TroyKomodo ): `62ce7ee4b6813bf221c8d43e`
and stopped after this emote ID: `62d40ad49be195fd6d68a23b`.

I assume this was fixed by https://github.com/SevenTV/API/commit/776565e8f66efc719cae09fdbe83e18953a991fd for emotes after that period, but a fix was not done to existing emotes. All of the emotes in that range still fail to render in chatterino7.

**Comment by AnatoleAM** [comment]
All uploads between July 12 and July 17 will not work on Chatterino and any clients which incorrectly implement dynamic URLs, until all emotes are re-processed and that compatibility layer can be turned back on.

In the meantime I encourage existing implementations to update how they use CDN URLs, and infer them from the API response rather than by hardcoding.
